#!/bin/sh
# postinst script for nfsbackup
#

[ -e /usr/lib/nfsbackup/systembackup_list ]
if [ $? -eq 0 ] ;then
rm -f /usr/lib/nfsbackup/systembackup_list
fi

[ -e /usr/lib/nfsbackup/backup_system_stat ]
if [ $? -eq 0 ] ;then
rm -f /usr/lib/nfsbackup/backup_system_stat
fi

rm /etc/grub.d/11_nfschina
update-grub

rm /boot/initrd_nfsrestore.img-3.19.8
